### ISSUE TITLE
6.1.3 Handling file deletions

### ISSUE THREAD

**Issue by lmjohansen** [frontend-tooling/sample-project-gulp#6]
Deleting files from cache don't work.
Looking into gulp watch found this:

_Moving from vinyl-fs watch (gaze) to chokidar_
[Link](https://github.com/gulpjs/gulp/commit/325fc8e7a1c8f3030643f6ac214e430cf343c725)

**Comment by lmjohansen** [comment]
https://github.com/gulpjs/gulp/blob/4.0/docs/recipes/handling-the-delete-event-on-watch.md

**Comment by ddprrt** [comment]
Again, thank you for that feedback :+1: 
Funny thing is: I was the one who included the switch from gaze to chokidar ;-) So I thought I already included the new code samples in ch6. I'll check with my editor, they should be be updated already. Keep you posted!

**Comment by lmjohansen** [comment]
Cache store the file name in posix style / my winbox use \... so my solution - should work for all os:

```
var slash = require('slash');

watcher.on('unlink',function(filepath){
  delete cached.caches['ugly'][slash(path.join(__dirname,filepath))];
  remember.forget('ugly', slash(path.join(__dirname,filepath)));
});
```

**Comment by ddprrt** [comment]
Cool! Is also in the book now.
