### ISSUE TITLE
blacklisted plug-ins

### ISSUE THREAD

**Issue by lmjohansen** [frontend-tooling/sample-project-gulp#7]
"gulp-minify-css": "deprecated. use gulp-cssnano." - gulp plugin used in start of book - should be replaced :-)

small stuff:
var blacklistURL should be blackListURL

.then(function(blacklist) should be blackList

**Comment by ddprrt** [comment]
The `minify-css` plugin has been removed in Chapter 2. We use CSS Nano now. Thanks for the update!

**Comment by ddprrt** [comment]
The other parts have been changed as well. Thank you!
